# Generated by Django 5.1.5 on 2025-03-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='table',
            name='seats',
        ),
        migrations.AddField(
            model_name='table',
            name='capacity',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
